package com.chanhbc.iother

@Suppress("unused")
object IConstant {

    const val INDEX_NOT_FOUND = -1
    const val INDEX_FIRST = 0
    const val ANDROID_SCHEMA = "http://schemas.android.com/apk/res/android"
    const val PERMISSION_AUTO_START = "permission_auto_start"
    const val REQUEST_CODE_DRAW_OVERLAY_PERMISSIONS = 6996
    const val MY_TAG = "bc"
    const val ANDROID_ASSET_FILE = "file:///android_asset/"
    const val FONTS_FOLDER = "fonts"
    const val JSON_FOLDER = "json"
    const val THEMES_FOLDER = "themes"
    const val BACKGROUND_FOLDER = "background"

    const val EMPTY = ""
    const val ELLIPSES = "…"
    const val GRAVE_ACCENT = "`"
    const val TILDE = "~"
    const val EXCLAMATION_MARK = "!"
    const val AT_SIGN = "@"
    const val NUMBER_SIGN = "#"
    const val DOLLAR_SIGN = "$"
    const val PERCENT_SIGN = "%"
    const val CARET = "^"
    const val AMPERSAND = "&"
    const val ASTERISK = "*"
    const val LEFT_PARENTHESIS = "("
    const val RIGHT_PARENTHESIS = ")"
    const val UNDERSCORE = "_"
    const val HYPHEN = "-"
    const val PLUS_SIGN = "+"
    const val EQUALS_SIGN = "="
    const val LEFT_CURLY_BRACE = "{"
    const val LEFT_SQUARE_BRACKET = "["
    const val RIGHT_CURLY_BRACE = "}"
    const val RIGHT_SQUARE_BRACKET = "]"
    const val VERTICAL_BAR = "|"
    const val BACKSLASH = "\\"
    const val ENTER = "\n"
    const val COLON = ":"
    const val SEMICOLON = ";"
    const val DOUBLE_QUOTATION_MARK = "\""
    const val APOSTROPHE = "\'"
    const val PERIOD = "."
    const val LESS_THAN_SIGN = "<"
    const val COMMA = ","
    const val GREATER_THAN_SIGN = ">"
    const val SLASH = "/"
    const val QUESTION_MARK = "?"
    const val SPACE = " "

    const val TTF = "ttf"
    const val OTF = "otf"
    const val FONT_DEFAULT_BOLD = "Quicksand_Bold.ttf"
    const val FONT_DEFAULT_SEMI_BOLD = "Quicksand_SemiBold.ttf"
    const val FONT_DEFAULT_MEDIUM = "Quicksand_Medium.ttf"
    const val FONT_DEFAULT_REGULAR = "Quicksand_Regular.ttf"
    const val FONT_DEFAULT_LIGHT = "Quicksand_Light.ttf"
    const val KEY_IS_RATE = "key_is_rate"
}
